### ISSUE TITLE
Problem getting parameters with post

### ISSUE THREAD

**Issue by flodi** [dannyvankooten/AltoRouter#141]
I've a simple login form that posts to /login/

Route is this:

$router->map( 'GET|POST', '/login/', function($login,$password) {
	require __DIR__ . '/views/login.php';
});

Catch route is:

if( $match && is_callable( $match['target'] ) ) {
	print_r($match);
	print_r($_REQUEST);
	call_user_func_array( $match['target'], $match['params'] ); 
} else {
	echo "Route not found";
}

The print_r shows me that $match['params']  and $_REQUEST are always empty.

I'm missing something?

Thank you

**Comment by koenpunt** [comment]
Can you show me the code of the form? 

And I'm pretty sure the `$login` and `$password` will never be passed to the function, because there are no params in the route definition.

Please also check the documentation and examples here: http://altorouter.com/

---

Ps. You can format your code by wrapping it in backticks;

    ```
    Code Here
    ```

**Comment by flodi** [comment]
Thank you for the answer. Was a n00b question, trying and testing, I was able to resolve it myself. GET and POST parameters work as usual, URL parameters works if - of course - defined in the routes.
