### ISSUE TITLE
Case-insensitive route matching

### ISSUE THREAD

**Issue by glumb** [dannyvankooten/AltoRouter#166]
It's quite common to match urls case-insensitive.

Is this possible with AltoRouter? Would be quite simple to `strtolower` the route and REQUEST_URI.

**Comment by koenpunt** [comment]
Using `strtolower` would make case insensitive matching no longer possible. Also, I don't find it common to make resources available on multiple urls. 
Do you have an example of where you would need that?

**Comment by glumb** [comment]
A lot of websites uses case-insensitive matching:
https://github.com/dannyvankooten/ALTOROUTER
https://github.com/dannyvankooten/altorouter
http://stackoverflow.com/dOcUmEnTaTiON

I don't mean that case-insensitive should be the default matching strategy, but giving an option to match case independent would be great.

**Comment by koenpunt** [comment]
> A lot of websites uses case-insensitive matching

I actually meant; do you have a personal usecase?

**Comment by glumb** [comment]
From a technical perspective I agree, that URLs should be unique and therefore case sensitive.

I don't have a special use case, thats just the way I want to handle urls. Domain names aren't case sensitive either, so I don't want to have case-sensitivity in the path.

**Comment by mastacontrola** [comment]
While I've made a TON of changes to my fork of this project (which is likely why I'm not pushing another PR (just too many for me to try to do a series of commits i think.)

You can take a look at https://github.com/mastacontrola/AltoRouter

Some of the things I've included are from many of the other pull requests as well.

Of note for this particular "issue" I've added a parameter that allows you to enable/disable case sensitivity.

Because I have the "defaultParameters" pull request associated the call on instantiation would look like:

```
$router = new AltoRouter(
    array(), // Set default routes,
    '', // Set base path
    array(), // Set additional matching types
    array(), // Set any default parameters
    false // Set case sensitivity (Default false)
);
```
Of course you can also switch routes to be case sensitive with:
```
$router->setIgnoreCase(true);
```

**Comment by dannyvankooten** [comment]
For anyone still reading this in 2019, here's how you can do this using AltoRouter.

1. Map all your routes in lowercase.

```php
$router->map( '/my-url', ...)
```

2. Match on the lowercased request URL.

```php
$match = $router->match(strtolower($_SERVER['REQUEST_URI']));
```
