### ISSUE TITLE
The match never happens

### ISSUE THREAD

**Issue by pyritewolf** [dannyvankooten/AltoRouter#184]
I'm sure I must be doing something wrong, but for the love of god I can't figure out what. Tbf I have a weird file structure so it's probably coming from that part.

The issue rn is that accessing a basic mapped route isn't working.

```
#File Structure
- web root
- - dev folder
- - - project subfolder
- - - - routing.php
- - - - AutoRouter.php
- - - - .htaccess
```

```
#project .htaccess
RewriteEngine On
RewriteBase /dev/project/
RewriteRule ^routing\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . routing.php [L]
```

```
#routing.php
require 'AltoRouter.php';
$router = new AltoRouter();
$router->setBasePath('/pyritewolf/comunidad');

$router->map( 'GET', '/', function() {
	echo "It worked!";
}, "home");

$router->map( 'GET', '/test/', function() {
	echo "banana";
});

$match = $router->match();
if( $match && is_callable( $match['target'] ) ) {
	call_user_func_array( $match['target'], $match['params'] );
} else {
	        // no route was matched
	echo "Ka-boom! It didn't work.";
}
```

Now, when I access http://webroot.com/dev/project/ I get a 404 error, which I'm guessing means the request didn't even go through routing.php. That probably has to do with my .htaccess, but I still haven't figured out how to fix it.

When I access http://webroot.com/dev/project/test it works perfectly.

Any ideas? I'm pretty sure I'm missing something rather stupid.

**Comment by mastacontrola** [comment]
Based on what I can see, and I'm no expert or anything, the issue is the rewrite.

Your current rewrite only rewrites to routing.php IF the uri filename and/or directory do not exist.

In your case http://webroot.com/dev/project/ the directory exists, where http://webroot.com/dev/project/test most likely doesn't.

I noticed a similar problem using nginx.

While I have no need to map any routes based on the root path directly, I'd imagine you may need to add another check so the psuedo code mite appear as:
```
If the file or directory do not exist, route to routing.php
If the directory does exist, but some file to test for doesn't, route to routing.php
```
For example:  If your root path doesn't have index.php (which from the info I'm seeing it may not) test for this file and rewrite to routing.php

I know this probably doesn't help fix the problem, but maybe it might help you see what's happening?

**Comment by mastacontrola** [comment]
Ran a simple test using information similar posted here.

The rewrite rule that works for my situation including routing the root path (even if it exists) is:
```
RewriteEngine On
RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-d
RewriteRule ^/(.*)$ routing.php [QSA,L]
```
Hopefully this helps.

**Comment by koenpunt** [comment]
I think the problem lies in 
`$router->setBasePath('/pyritewolf/comunidan');`, which probably should be `$router->setBasePath('/dev/project');`

**Comment by koenpunt** [comment]
That and server rewriting like @mastacontrola mentioned. Also depends where your `.htaccess` file resides

**Comment by mastacontrola** [comment]
@koenpunt It would seem the pyritewolf/comunidan was working fine at least if you consider the /test route worked, but the '/' did not.
