### ISSUE TITLE
Poorly formed URL matching

### ISSUE THREAD

**Issue by mastacontrola** [dannyvankooten/AltoRouter#189]
Hello guys, figured I'd come up with a better solution to resolving poorly formed url mappings not matching.

By poorly formed url mappings I'm specifying urls that my have excessive slashes as might occur when a url is dynamically generated.  For example, a route my be specified as:
`/[some|path]`

But when you make the url to click on it might come up with a link like:

```
http://x.x.x.x//////some////////
```

The current routing system doesn't allow the poorly formed routes because it doesn't nearly exactly match the `/some` or `/path`.  The same can be said with the trailing slash. If you add even a single / (as might automatically happen in some browsers) to the route the whole thing fails. You can kind of get around with making your route `/[some|path]/?`.  While this works it allows a route of `/some`, `/some/`, and `/some/?`.  This certainly isn't the end of the world but I think I found a cleaner method.

I propose slightly modifying the regex generation to:
```
$pattern = '(?:'
    . ('' !== $pre ? $pre.'+' : null)
    . '('
    . ('' !== $param ? "?P<$param>" : null)
    . $type
    . ')'
    . $optional
    . '(/+|))'
    . $optional;
```

The only differences between the current and this is the $pre and between the two optionals.
The pre is normally just:
```
    . ('' !== $pre ? $pre : null)
```
The between the two optionals is normally just:
```
    . ')'
```

This brings the proper return of the expected item too, which required a slight mod to the AltoRouterTest.php file.  I don't know which line, but it makes the barurl checks require the 'page' => '' array element.

I know this is a lot of information but I would think if you have a bare url, it should have the parameter expected anyway.

**Comment by dannyvankooten** [comment]
Hey @mastacontrola,

This is actually by design, as accepting the same route with and without the trailing slash is not how [the HTTP specification](https://www.w3.org/Addressing/URL/uri-spec.html) works. Search engines build on this by treating the two as 2 separate resources, so accepting two URL's to point to the same thing is actually a SEO issue too. 

People should be addressing for this in their applications by either redirecting to the with-trailing-slash or the without-trailing-slash version of any given page / resource. 

As for the poorly formed URL's, I'm really not sure why we should have the router accept such URL's. Wouldn't it be much better to fix the URL generation instead?

Thanks for your thoughts!

**Comment by mastacontrola** [comment]
While I'm all about fixing the url's to be proper, I'm just thinking in terms of all the many programming mistakes people make. Something as simple of a slash is easily missed.  But I do agree, if you're making a route, it should follow that route only.

I've been doing work, normally, to make things easier for people so that may be where my mindset was.  I'm not at all trying to say we should fix other people's programming mistakes, rather just trying to keep things alive and well.
