### ISSUE TITLE
Multiple Route to single target

### ISSUE THREAD

**Issue by amuagarwal** [dannyvankooten/AltoRouter#191]
Hi 

Need a small help how can i merge multiple route to single target e.g i have /login and /verifyloin both point to same page with query string. 

Another query is how to merge /login and /login/ rather than writing 2 maps.

**Comment by dannyvankooten** [comment]
Hi @amuagarwal,

I'd simply match both routes to the same "target" separately, since they are essentially two different URL's.

```php
$router->map('GET', '/login', 'callback_fn_name' );
$router->map('GET', '/verifylogin', 'callback_fn_name' );
```

I do not recommend mapping the URL with and without the trailing slash since this means that two different URL's point to the same page, which is a SEO issue and goes against the HTTP specification. You should pick one (with or without trailing slash) and stick to that.

You can redirect to the non-trailing slash version of a PHP page using the following code, but it might be better to configure this in nginx or Apache instead.
```php
if( strpos( $_SERVER['REQUEST_URI'], -1 ) === '/' ) ) {
     $url = substr( $_SERVER['REQUEST_URI'], 0, -1 );
     header("Location: $url"); 
     exit;
}
```

Good luck!
