### ISSUE TITLE
Class as callable?

### ISSUE THREAD

**Issue by jozydapozy** [dannyvankooten/AltoRouter#193]
I see this in the documentation: `$router->map( 'GET', '/users/[i:id]/', 'UserController#showDetails' );`
What does that `#` mean?
Something like this doesn't seem to match:

	class UserController {
		public static function showDetails($id) {
			echo $id;
		}
	}

Is there some example code for this?

**Comment by dannyvankooten** [comment]
Hi @jozydapozy,

AltoRouter leaves the actual dispatching up to you, so the third parameter of the `map` method can be anything you want that you can use to determine what code should be called.

In the example, the string could be split on `#` so that the code knows to create an instance of `UserController` and call the `showDetails` method on it. It's just an example though.

**Comment by jozydapozy** [comment]
Thanks, I understand. Maybe you should mention this somewhere in the documentation.
