### ISSUE TITLE
[documentation] example using custom regex in route (start with @)

### ISSUE THREAD

**Issue by ncou** [dannyvankooten/AltoRouter#209]
Hi,

In the documentation about the route, there is a sentense : 

http://altorouter.com/usage/mapping-routes.html
"This is the route pattern to match against. This can be a plain string, one of the predefined regex filters or a custom regex. Custom regexes must start with @"

But there is no example. Don't you think an example should be added ? How do you use this option ?

it could be usefull for the users (my 2 cents opinion).

Keep up the good work.

**Comment by koenpunt** [comment]
Hi @ncou, the "must start with @" is pretty literal; instead of using a parameter string `[:controller]/[:action]`, you use a string which starts with a `@`, for example one with named patterns; `@^(?<controller>.*?)\/(?<action>.*?)$`

In the test file there's a [trivial example](https://github.com/dannyvankooten/AltoRouter/blob/master/tests/AltoRouterTest.php#L433) and also a more [advanced example](https://github.com/dannyvankooten/AltoRouter/blob/master/tests/AltoRouterTest.php#L447-L459).

If you want to add an example to the website, please make a PR to the [`gh-pages` branch](https://github.com/dannyvankooten/AltoRouter/tree/gh-pages)

**Comment by koenpunt** [comment]
In addition, here's how the regex is used: [AltoRouter.php#L206-L209](https://github.com/dannyvankooten/AltoRouter/blob/master/AltoRouter.php#L206-L209)
