### ISSUE TITLE
Bug in stripping of base path from request url

### ISSUE THREAD

**Issue by Stanzi1791** [dannyvankooten/AltoRouter#222]
Line 183:
`$requestUrl = substr($requestUrl, strlen($this->basePath));`

Should be changed to something like:
`$requestUrl = preg_replace('/^' . preg_quote($this->basePath, '/') . '/', '', $requestUrl);`

Right now it is stripping the number of characters that $this->basePath is long from the beginning of $requestUrl, without checking that $requestUrl actually starts with $bashPath before stripping.

**Comment by dannyvankooten** [comment]
Hi @Stanzi1791,

Wouldn't that be an implementation bug instead? I can definitely see why the check would be useful but since it's an operation that has to be performed on every request, I'd say it's most likely better to fix the implementation instead. Thoughts?

**Comment by koenpunt** [comment]
That's definitely an implementation detail. The `basePath` is there for when you did set up your php application anywhere else than root (`/`).

There's no point in specifying a `basePath` otherwise, because you can simply have explicit routes defined.

But if you really think this is a library issue, please elaborate and provide a use case and/or example to support your thoughts.
