### ISSUE TITLE
Offset operations support for $router->match()

### ISSUE THREAD

**Issue by Atulin** [dannyvankooten/AltoRouter#228]
Code taken from the docs:
```php
$match = $router->match();

// Handle routing
if( $match && is_callable( $match['target'] ) ) {
    call_user_func_array( $match['target'], $match['params'] );
} else {
    // no route was matched
    header($_SERVER['SERVER_PROTOCOL'] . ' 404 Not Found');
    die('404');
}
```
Contains errors, according to PHPStorm:
![image](https://user-images.githubusercontent.com/11233299/52829836-a3bd5000-30ce-11e9-8928-e4536a8efa25.png)

**Comment by dannyvankooten** [comment]
It's not an actual issue but due to an inconsistency in the API that PHPStorm can't make sense of yet. `$router->match()` returns false when no routes were matched, or an array when a route was matched. 

The first condition makes sure that the latter offset operations will always work. That said, if you change the code to the following then PHPStorm will stop complaining.

```php
$match = $router->match();

// Handle routing
if( is_array($match) && is_callable( $match['target'] ) ) {
    call_user_func_array( $match['target'], $match['params'] );
} else {
    // no route was matched
    header($_SERVER['SERVER_PROTOCOL'] . ' 404 Not Found');
    die('404');
}
```

**Comment by dannyvankooten** [comment]
I've [updated the docs to reflect this](http://altorouter.com/usage/processing-requests.html). Thanks for the input @Atulin!

**Comment by Atulin** [comment]
Thank you, I'll update my code.

**Comment by Atulin** [comment]
I'm afraid it did not fix the issue.
Still, at least now I know that it's working as intended despite the error shown 👌
![image](https://user-images.githubusercontent.com/11233299/53065224-11042300-34cb-11e9-849e-05b63fcf19f8.png)
