### ISSUE TITLE
How to implement put,delete method?

### ISSUE THREAD

**Issue by kabircse** [dannyvankooten/AltoRouter#246]
How to use other method such as put,delete and patch. I tried several times but failed. Could you give me an example of put and patch method ?

My Code:

           $router->map('PUT','/employee/update/[i:id]', 'EmployeeController@update');

Form:

             <form method="post" action="//127.0.0.1/employee/update/1">
                   <input type="hidden" name="_method" value="put" />
                   <input type="text" name="age" value="25" />
                   <input type="submit" value="Update" />
             </form>

But it works when I changed router map put to post.

**Comment by zazy** [comment]
In HTTP 1.x standard only accepted methods for form submission is GET and POST. You can't send a PUT request to your HTTP server that way.

**Comment by kabircse** [comment]
> In HTTP 1.x standard only accepted methods for form submission is GET and POST. You can't send a PUT request to your HTTP server that way.

How laravel implemented these methods ?

**Comment by zazy** [comment]
Laravel implement this  method intercepting the POST of the form and analyzing the _method hidden field. If you use Laravel you should use its routing features.
If you're not using Laravel you have to emulate it at an higher level than AltoRouter so that you have not to do the job again if you have to update.
